# Generated by Django 4.2.7 on 2024-11-27 14:52

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название раздела')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
                'db_table': 'chapter',
            },
        ),
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название темы урока')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.chapter', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'db_table': 'theme',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название урока')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('annotation', models.TextField(blank=True, null=True, verbose_name='Описание урока')),
                ('video_lesson', models.URLField(blank=True, null=True, verbose_name='Видео урока')),
                ('audio_lesson', models.FileField(blank=True, null=True, storage=main.models.AudioStorage(), upload_to='', verbose_name='Аудиозапись урока')),
                ('audiofile_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Id аудиофайла в ТГ')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.themes', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'db_table': 'lesson',
            },
        ),
    ]
