# Generated by Django 4.2.16 on 2024-10-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_lesson',
            field=models.URLField(blank=True, null=True, verbose_name='Видео урока'),
        ),
    ]
