# Generated by Django 4.2.16 on 2024-10-28 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_lesson_video_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telegram_file_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audiofile_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Id аудиофайла в ТГ')),
                ('text_file_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Id текстового файла в ТГ')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lesson', verbose_name='Название урока')),
            ],
            options={
                'verbose_name': 'ИД файлов в телеграмме',
                'db_table': 'telegram_file_id',
            },
        ),
    ]
