# Generated by Django 4.2.7 on 2024-11-21 11:03

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_telegram_file_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сhapter',
            new_name='Chapter',
        ),
        migrations.RenameModel(
            old_name='Telegram_file_id',
            new_name='TelegramFileId',
        ),
        migrations.AlterModelOptions(
            name='telegramfileid',
            options={'verbose_name': 'ИД файлов в телеграмме', 'verbose_name_plural': 'ИД файлов в телеграмме'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='audio_lesson',
            field=models.FileField(blank=True, null=True, storage=main.models.AudioStorage(), upload_to='', verbose_name='Аудиозапись урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='text_lesson',
            field=models.FileField(blank=True, null=True, storage=main.models.TextStorage(), upload_to='', verbose_name='Текст урока'),
        ),
    ]
